title: "Docs"
metadataformat: "yaml"
# enableGitInfo so lastmod in sitemap.xml is based off git
enableGitInfo: false
canonifyURLs: true
pygmentsuseclasses: true
pygmentsCodeFences: true

# taxonomies
taxonomies:
  tag: "tags"
  category: "categories"
  "video-category": "video-categories"

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# set this as a default otherwise we get "Error: found overlapping content dirs"
contentDir: "content/en"

# gitinfo vars
enableGitInfo: true

# Allow to render HTML in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
