title: "Docs"
metadataformat: "yaml"
# enableGitInfo so lastmod in sitemap.xml is based off git
canonifyURLs: true
pygmentsuseclasses: true
pygmentsCodeFences: true

publishDir: "./public"

# taxonomies
taxonomies:
  #tag: "tags"
  #category: "categories"
  "video-category": "video-categories"

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

# set this as a default otherwise we get "Error: found overlapping content dirs"
# contentDir: "content/en"

# gitinfo vars
enableGitInfo: true

# Allow to render HTML in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true

module:
  imports:
   - path: github.com/DataDog/websites-modules
     disabled: false
     mounts:
     - source: layouts/partials/nav/main-nav.html
       target: layouts/partials/nav/main-nav.html
     - source: layouts/partials/nav/nav-logo-download.html
       target: layouts/partials/nav/nav-logo-download.html
     - source: layouts/partials/nav/menu-mobile.html
       target: layouts/partials/nav/menu-mobile.html
     - source: layouts/partials/nav/mobile-documentation.html
       target: layouts/partials/nav/mobile-documentation.html
     - source: layouts/partials/search-bar.html
       target: layouts/partials/search-bar.html
     - source: layouts/partials/announcement_banner.html
       target: layouts/partials/announcement_banner.html
     - source: assets/styles/components/_announcement-banner.scss
       target: assets/styles/components/_announcement-banner.scss
     - source: assets/styles/base/_variables.scss
       target: assets/styles/base/_modules_variables.scss
     - source: assets/styles/components/_main-nav.scss
       target: assets/styles/components/_main-nav.scss
     - source: assets/styles/components/_mobile-nav.scss
       target: assets/styles/components/_mobile-nav.scss
     - source: assets/styles/base/_iconfont.scss
       target: assets/styles/base/_iconfont.scss
     - source: static/fonts/iconfont.woff2
       target: static/fonts/iconfont.woff2
     - source: static/fonts/iconfont.woff
       target: static/fonts/iconfont.woff

  mounts:
    # default mounts
    - source: content/en
      target: content
      lang: en
    - source: content/fr
      target: content
      lang: fr
    - source: content/ja
      target: content
      lang: ja
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: static
      target: assets
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes
    # custom mounts
    - source: "./node_modules/@datadog/browser-rum/bundle/datadog-rum.js"
      target: "assets/node_modules/datadog-rum.js"
    - source: "./node_modules/@datadog/browser-logs/bundle/datadog-logs.js"
      target: "assets/node_modules/datadog-logs.js"
