en:
  languageName: "English"
  weight: 1
  outputs:
    home:
      - HTML
      - RSS
      - Search
      - Partners
      - Redirects
    page:
      - HTML

fr:
  languageName: "Français"
  weight: 2
ja:
  languageName: "日本語"
  weight: 3
ko:
  languageName: "한국어"
  weight: 4
es:
  languageName: "Español"
  weight: 5
studio:
  languageName: "Studio"
  weight: 6
