site_name: "Datadog Infrastructure and Application Monitoring"
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "This page is not yet available in English, we are working on its translation. <br> May you have any questions or feedback about our current translation project, <a href=\"https://docs.datadoghq.com/fr/help/\">feel free to reach out to us!</a>"
announcement_banner:
  desktop_message: "Datadog Webinar: Security Strategy for Cloud Applications"
  mobile_message: "Webinar: Security Strategy for Cloud Applications"
  external_link: "https://www.datadoghq.com/event/security-strategy-24/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=dg-security-ww-docs-announcement-livewebinar-securitystrategyQ424"
translate_status_banner: "This translation isn't up-to-date. For the latest English version, click here"
