announcement_banner:
  desktop_message: Datadog named a Leader in the Gartner® Magic Quadrant™ for Observability
    Platforms
  external_link: https://www.datadoghq.com/resources/gartner-magic-quadrant-observability-platforms-2025/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=dg-apm-ww-announcement-corpsite-announcement-gartnermq2025-obsplat
  mobile_message: Leader in the Gartner® Magic Quadrant™
disclaimer: 이 페이지는 아직 한국어로 제공되지 않습니다. 번역 작업 중입니다. <br>현재 번역 프로젝트에 대한 질문이나 피드백이 있으신
  경우<a href="https://docs.datadoghq.com/fr/help/"> 언제든지 연락주시기 바랍니다.</a>
meta_description: 클라우드 스케일 모니터링의 선두주자, Datadog
meta_title: Datadog로 시작하기
site_name: Datadog 인프라스트럭처 및 응용 프로그램 모니터링
site_support_banner: 이 제품은 선택한 <a href="/getting_started/site">Datadog 사이트</a>에서 지원되지
  않습니다.
translate_status_banner: 이 번역은 최신 버전이 아닙니다. 최신 영문 버전을 보려면 여기를 클릭하세요.
