site_name: "Datadog 인프라 및 애플리케이션 모니터링"
meta_title: Datadog 시작하기
meta_description: "Datadog, 클라우드 규모 모니터링 서비스 선도 기업."
disclaimer: "이 페이지는 아직 영어로 제공되지 않습니다. 현재 번역 중입니다. <br> Datadog의 현재 진행 중인 번역 프로젝트에 관한 질문이 있거나 피드백을 주시려면 <a href=\"https://docs.datadoghq.com/help/\">자유롭게 문의하세요!</a>"
announcement_banner:
    desktop_message: '2025년 컨테이너 및 서버리스 현황 보고서를 읽어보세요!'
    mobile_message: '컨테이너 및 서버리스 현황 보고서를 읽어보세요!'
    external_link: 'https://www.datadoghq.com/state-of-containers-and-serverless/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=int-infra-ww-announcement-product-announcement-containers-serverless-2025'
translate_status_banner: "이 번역은 최신 버전이 아닙니다. 최신 영어 버전을 보려면 여기 클릭"
site_support_banner: "이 제품은 선택하신 <a href=\"/getting_started/site\">Datadog 사이트</a>에서는 지원되지 않습니다."
