site_name: "Datadog Infrastructure and Application Monitoring"
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "This page is not yet available in Spanish. We are working on its translation. <br> If you have any questions or feedback about our current translation project, <a href=\"https://docs.datadoghq.com/es/help/\">feel free to reach out to us!</a>"
announcement_banner:
  desktop_message: '<i class="icon-right-arrow-slim text-white"></i><span>NOW LIVE: Datadog launches availability zone in Australia to support local data residency</span><span>Learn More</span>'
  mobile_message: 'Datadog launches availability zone in Australia'
  background_color: "#6300D4"
  icon_color: "#ffffff"
  custom_classes: 'dash-announcement-banner'
  external_link: https://www.datadoghq.com/about/latest-news/press-releases/datadog-launches-new-availability-zone-in-australia
translate_status_banner: "This translation isn't up-to-date. For the latest English version, click here"
site_support_banner: "This product is not supported for your selected <a href=\"/getting_started/site\">Datadog site</a>."
