announcement_banner:
  desktop_message: '<i class="icon-right-arrow-slim text-white"></i><span>NOW LIVE: Datadog launches availability zone in Australia to support local data residency</span><span>Learn More</span>'
  mobile_message: 'Datadog launches availability zone in Australia'
  background_color: "#6300D4"
  icon_color: "#ffffff"
  custom_classes: 'dash-announcement-banner'
  external_link: https://www.datadoghq.com/about/latest-news/press-releases/datadog-launches-new-availability-zone-in-australia
disclaimer: 이 페이지는 아직 영어로 제공되지 않습니다. 번역 작업 중입니다. <br>현재 번역 프로젝트에 대한 질문이나 피드백이 있으신
  경우<a href="https://docs.datadoghq.com/ko/help/"> 언제든지 연락주시기 바랍니다.</a>
meta_description: 클라우드 스케일 모니터링의 선두주자, Datadog
meta_title: Datadog로 시작하기
site_name: Datadog 인프라스트럭처 및 응용 프로그램 모니터링
translate_status_banner: 이 번역은 최신 버전이 아닙니다. 최신 영문 버전을 보려면 여기를 클릭하세요.
site_support_banner: "This product is not supported for your selected <a href=\"/getting_started/site\">Datadog site</a>."
