site_name: "Datadog Infrastructure and Application Monitoring"
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "This page is not yet available in English, we are working on its translation. <br> May you have any questions or feedback about our current translation project, <a href=\"https://docs.datadoghq.com/fr/help/\">feel free to reach out to us!</a>"
announcement_banner:
  desktop_message: "Read the 2023 State of Cloud Security Study!"
  mobile_message: "Read the 2023 Cloud Security Study!"
  external_link: "https://www.datadoghq.com/state-of-cloud-security/?utm_source=organic&utm_medium=display&utm_campaign=dg-organic-websites-ww-docs-announcement-report-cloudsecurity2023"
exclude: []
translate_status_banner: "This translation isn't up to date, for the latest english version click here"
