site_name: "Datadog Infrastructure and Application Monitoring"
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "This page is not yet available in English. We are working on its translation. <br> If you have any questions or feedback about our current translation project, <a href=\"https://docs.datadoghq.com/fr/help/\">feel free to reach out to us!</a>"
announcement_banner:
  desktop_message: "Read the 2024 State of Cloud Security Study!"
  mobile_message: "Read the State of Cloud Security Study!"
  external_link: "https://www.datadoghq.com/state-of-cloud-security/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=dg-security-ww-docs-announcement-report-cloudsecurity2024"
translate_status_banner: "This translation isn't up-to-date. For the latest English version, click here"
