site_name: "Monitorización de la infraestructura y las aplicaciones de Datadog"
meta_title: Empezando con Datadog
meta_description: "Datadog, el servicio líder de monitorización a escala en nube."
disclaimer: "Esta página aún no está disponible en español. Estamos trabajando en su traducción. <br> Si tiene alguna pregunta o comentario sobre nuestro proyecto de traducción actual, <a href=\"https://docs.datadoghq.com/help/\">¡no dude en contactarnos!</a>"
announcement_banner:
    desktop_message: '¡Lea el Informe sobre el estado de los contenedores y los servidores sin servidor de 2025!'
    mobile_message: '¡Lea el informe sobre el estado de los contenedores y los servidores sin servidor!'
    external_link: 'https://www.datadoghq.com/state-of-containers-and-serverless/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=int-infra-ww-announcement-product-announcement-containers-serverless-2025'
translate_status_banner: "Esta traducción no está actualizada. Para ver la última versión en inglés, haga clic aquí"
site_support_banner: "Este producto no es compatible con el <a href=\"/getting_started/site\">sitio Datadog</a>seleccionado."
