site_name: "Surveillance d'applications et d'infrastructures avec Datadog"
meta_title: Débuter avec Datadog
meta_description: "Datadog, le principal prestataire de services de surveillance à l'échelle du cloud."
disclaimer: "Cette page n'est pas encore disponible en anglais. Nous travaillons sur sa traduction. <br> Si vous avez des questions ou des retours sur notre projet de traduction actuel, <a href=\"https://docs.datadoghq.com/help/\">n'hésitez pas à nous contacter !</a>"
announcement_banner:
    desktop_message: 'Lisez le rapport 2025 sur l''état des conteneurs et des serveurs sans serveur !'
    mobile_message: 'Lisez le rapport sur l''état des conteneurs et des serveurs sans serveur !'
    external_link: 'https://www.datadoghq.com/state-of-containers-and-serverless/?utm_source=inbound&utm_medium=corpsite-display&utm_campaign=int-infra-ww-announcement-product-announcement-containers-serverless-2025'
translate_status_banner: "Cette traduction n'est pas à jour. Pour la dernière version en anglais, cliquez ici"
site_support_banner: "Ce produit n'est pas pris en charge pour votre <a href=\"/getting_started/site\">site Datadog sélectionné</a>."
