site_name: "Datadog Infrastructure and Application Monitoring"
meta_image: datadog_logo_share_tt.png
meta_title: Getting Started with Datadog
meta_description: Datadog, the leading service for cloud-scale monitoring.
disclaimer: "This page is not yet available in English, we are working on its translation. <br> May you have any questions or feedback about our current translation project, <a href=\"https://docs.datadoghq.com/fr/help/\">feel free to reach out to us!</a>"
announcement_banner:
  desktop_message: "Announcing Sensitive Data Scanner for data protection at scale!"
  mobile_message: "Announcing Datadog Sensitive Data Scanner!"
  external_link: 'https://www.datadoghq.com/product/sensitive-data-scanner/'
exclude: []
translate_status_banner: "This translation isn't up to date, for the latest english version click here"
