title: "Docs"
baseURL: "http://localhost:1313/"
metadataformat: "yaml"

canonifyURLs: true
pygmentsuseclasses: true

# taxonomies
taxonomies:
  tag: "tags"
  video: "videos"
  example: "examples"
preserveTaxonomyNames: true

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    #languageName: "English"
    #languageCode: "en-US"
    disclaimer: ""
    weight: 0
    menu:
      main_references:
        - identifier: menu_references_api
          name: "API"
          url: "/api/"
          weight: 10
        - identifier: menu_references_tracing
          name: "Tracing"
          url: "/tracing/"
          weight: 20
        - identifier: menu_references_libraries
          name: ""
          url: "/libraries/"
          weight: 30
        - identifier: menu_references_monitoring
          name: ""
          url: "/monitoring/"
          weight: 40
        - identifier: menu_references_graphing
          name: ""
          url: "/graphing/"
          weight: 50
        - identifier: menu_references_host_names
          name: ""
          url: "/hostnames/"
          weight: 60
        - identifier: menu_references_integrations
          name: ""
          url: "/integrations/"
          weight: 70
        - identifier: menu_references_dogstatsd
          name: ""
          url: "/guides/dogstatsd/"
          weight: 80
        - identifier: menu_references_examples
          name: ""
          url: "/examples/"
          weight: 90
        - identifier: menu_references_videos
          name: ""
          url: "/videos/"
          weight: 100
        - identifier: menu_references_billing
          name: ""
          url: "/guides/billing/"
          weight: 110
        - identifier: menu_references_faq
          name: ""
          url: "/faq/"
          weight: 120
      basic_agent:
        - identifier: amazonlinux
          name: "Amazon Linux"
          url: guides/basic_agent_usage/amazonlinux/
          weight: 10

        - identifier: centos
          name: "CentOs"
          url: guides/basic_agent_usage/centos/
          weight: 20

        - identifier: docker
          name: "CoreOS/Docker"
          url: guides/basic_agent_usage/docker/
          weight: 30

        - identifier: deb
          name: "Debian"
          url: guides/basic_agent_usage/deb/
          weight: 40

        - identifier: fedora
          name: "Fedora"
          url: guides/basic_agent_usage/fedora/
          weight: 50

        - identifier: osx
          name: "Mac OS X"
          url: guides/basic_agent_usage/osx/
          weight: 60

        - identifier: redhat
          name: "Red Hat"
          url: guides/basic_agent_usage/redhat/
          weight: 70

        - identifier: ubuntu
          name: "Ubuntu"
          url: guides/basic_agent_usage/ubuntu/
          weight: 80

        - identifier: windows
          name: "Windows"
          url: guides/basic_agent_usage/windows/
          weight: 90

        - identifier: source
          name: "From Source"
          url: guides/basic_agent_usage/source/
          weight: 100
      tracingnav:
        - identifier: customnav_tracingnav_tracing
          url: #
          weight: 10

        - identifier: customnav_tracingnav_install
          url: tracing/
          weight: 20

        - identifier: customnav_tracingnav_terminology
          url: tracing/terminology/
          weight: 30

        - identifier: customnav_tracingnav_faq
          url: tracing/faq/
          weight: 40

        - identifier: customnav_tracingnav_langs
          url: #
          weight: 50

        - identifier: customnav_tracingnav_go
          url: tracing/go/
          weight: 60

        - identifier: customnav_tracingnav_python
          url: tracing/python/
          weight: 70

        - identifier: customnav_tracingnav_ruby
          url: tracing/ruby/
          weight: 80

        - identifier: customnav_tracingnav_api
          url: tracing/api/
          weight: 90

  ja:
    #languagename: "日本語"
    weight: 1
    disclaimer: "アクセスいただきありがとうございます。こちらのページは現在英語のみのご用意となっております。引き続き日本語化の範囲を広げてまいりますので、皆様のご理解のほどよろしくお願いいたします。"
    menu:
      main_references:
        - identifier: menu_references_api
          name: "API"
          url: "/api/"
          weight: 10
        - identifier: menu_references_tracing
          name: "Tracing"
          url: "/tracing/"
          weight: 20
        - identifier: menu_references_libraries
          name: ""
          url: "/libraries/"
          weight: 30
        - identifier: menu_references_monitoring
          name: ""
          url: "/monitoring/"
          weight: 40
        - identifier: menu_references_graphing
          name: ""
          url: "/graphing/"
          weight: 50
        - identifier: menu_references_host_names
          name: ""
          url: "/hostnames/"
          weight: 60
        - identifier: menu_references_integrations
          name: ""
          url: "/integrations/"
          weight: 70
        - identifier: menu_references_dogstatsd
          name: ""
          url: "/guides/dogstatsd/"
          weight: 80
        - identifier: menu_references_examples
          name: ""
          url: "/examples/"
          weight: 90
        - identifier: menu_references_videos
          name: ""
          url: "/videos/"
          weight: 100
        - identifier: menu_references_billing
          name: ""
          url: "/guides/billing/"
          weight: 110
        - identifier: menu_references_faq
          name: ""
          url: "/faq/"
          weight: 120

params:
  environment: local
  img_url: "http://localhost:1313/"
  imgix:
    header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
    header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
    header_gif: "?ch=Width,Save-Data&fm=gif"
    jpg: "?fm=jpg&auto=format&lossless=true"
    png: "?fm=png&auto=format&lossless=1"
    gif: ""
  static_url: "http://localhost:1313/"
  code_languages:
    - Python
    - Ruby
    - Console
  footer_scripts:
    - snowplow: false
    - marketo: false
    - adroll: false
