title: "Docs"
baseURL: "http://localhost:1313/"
metadataformat: "yaml"
# enableGitInfo so lastmod in sitemap.xml is based off git
enableGitInfo: true
canonifyURLs: true
pygmentsuseclasses: true
pygmentsCodeFences: true

# taxonomies
taxonomies:
  tag: "tags"
  video: "videos"
preserveTaxonomyNames: true

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    #languageName: "English"
    #languageCode: "en-US"
    disclaimer: ""
    weight: 0
    contentDir: content/en
  fr:
    disclaimer: "Cette page n'est pas encore disponible en Fran√ßais, nous travaillons actuellement sur sa traduction.<br> Si vous avez des questions ou des retours sur ce projet de traduction, <a href=\"https://docs.datadoghq.com/fr/help/\">contactez-nous!</a>"
    weight: 0
    contentDir: content/fr

params:
  environment: local
  img_url: "http://localhost:1313/"
  corp_url: "https://www.datadoghq.com/"
  imgix:
    header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
    header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
    header_gif: "?ch=Width,Save-Data&fm=gif"
    jpg: "?fm=jpg&auto=format&lossless=true"
    png: "?fm=png&auto=format&lossless=1"
    gif: ""
  static_url: "http://localhost:1313/"
  announcement_banner:
    text: "The <strong>Service Map</strong> for APM is here!"
    link: "blog/service-map/"
    exclude: []
  code_languages:
    - display_name: Python
      key: python
    - display_name: Ruby
      key: ruby
    - display_name: Curl
      key: bash
  footer_scripts:
    - snowplow: false
    - marketo: false
    - adroll: false
  home:
      meta_image: datadog_logo_share_tt.png
      meta_title: Getting Started with Datadog
      meta_description: Datadog, the leading service for cloud-scale monitoring.
