title: "Docs"
baseURL: "http://localhost:1313/"
metadataformat: "yaml"

canonifyURLs: true
pygmentsuseclasses: true

# taxonomies
taxonomies:
  tag: "tags"
  video: "videos"
  example: "examples"
preserveTaxonomyNames: true

# language
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false

languages:
  en:
    #languageName: "English"
    #languageCode: "en-US"
    disclaimer: ""
    weight: 0
    menu:

# Home Page
      main:
        - identifier: menu_references_getting_started
          name: "Getting Started"
          url: "/getting_started/"
          pre: "nav_start"
          weight: 30

        # AGENT
        - identifier: menu_references_agent
          name: "Agent"
          url: "/agent/"
          pre: "nav_agent"
          weight: 40
        # AGENT - Subnav start
        - identifier: customnav_agentnav_basic_usage
          name: "Basic Agent Usage"
          url: "/agent/basic_agent_usage/"
          weight: 10
          parent: menu_references_agent
        - identifier: amazonlinux
          name: "Amazon Linux"
          url: "/agent/basic_agent_usage/amazonlinux/"
          weight: 10
          parent: customnav_agentnav_basic_usage
        - identifier: centos
          name: "CentOs"
          url: "/agent/basic_agent_usage/centos/"
          weight: 20
          parent: customnav_agentnav_basic_usage
        - identifier: docker
          name: "CoreOS/Docker"
          url: "/agent/basic_agent_usage/docker/"
          weight: 30
          parent: customnav_agentnav_basic_usage
        - identifier: deb
          name: "Debian"
          url: "/agent/basic_agent_usage/deb/"
          weight: 40
          parent: customnav_agentnav_basic_usage
        - identifier: customnav_agentnav_install_debian_5
          name: "Debian Install"
          url: "/agent/basic_agent_usage/install_debian_5/"
          weight: 50
          parent: customnav_agentnav_basic_usage
        - identifier: fedora
          name: "Fedora"
          url: "/agent/basic_agent_usage/fedora/"
          weight: 60
          parent: customnav_agentnav_basic_usage
        - identifier: osx
          name: "Mac OS X"
          url: "/agent/basic_agent_usage/osx/"
          weight: 70
          parent: customnav_agentnav_basic_usage
        - identifier: redhat
          name: "Red Hat"
          url: "/agent/basic_agent_usage/redhat/"
          weight: 80
          parent: customnav_agentnav_basic_usage
        - identifier: ubuntu
          name: "Ubuntu"
          url: "/agent/basic_agent_usage/ubuntu/"
          weight: 90
          parent: customnav_agentnav_basic_usage
        - identifier: windows
          name: "Windows"
          url: "/agent/basic_agent_usage/windows/"
          weight: 100
          parent: customnav_agentnav_basic_usage
        - identifier: source
          name: "From Source"
          url: "/agent/basic_agent_usage/source/"
          weight: 110
          parent: customnav_agentnav_basic_usage
        - identifier: customnav_agentnav_agent_checks
          name: "Agent Checks"
          url: "/agent/agent_checks/"
          weight: 30
          parent: menu_references_agent
        - identifier: customnav_agentnav_autodiscovery
          name: "Autodiscovery"
          url: "/agent/autodiscovery/"
          weight: 40
          parent: menu_references_agent
        - identifier: customnav_agentnav_faq
          name: "Faq"
          url: "/agent/faq/"
          weight: 50
          parent: menu_references_agent
        - identifier: customnav_agentnav_installcoreextra
          name: "Install Core Extra"
          url: "/agent/installcoreextra/"
          weight: 60
          parent: menu_references_agent
        - identifier: customnav_agentnav_logs
          name: "Logs"
          url: "/agent/logs/"
          weight: 70
          parent: menu_references_agent
        - identifier: customnav_agentnav_tagging
          name: "Tagging"
          url: "/agent/tagging/"
          weight: 80
          parent: menu_references_agent
        # AGENT - Subnav end


        # INTEGRATIONS
        - identifier: menu_references_integrations
          name: "Integrations"
          url: "/integrations/"
          pre: "nav_integrations"
          weight: 50
        # INTEGRATIONS - Subnav start
        # INTEGRATIONS - Subnav end


        # GRAPHING
        - identifier: menu_references_graphing
          name: "Graphing/Visualization"
          url: "/graphing/"
          pre: "nav_graphing"
          weight: 60
        # GRAPHING - Subnav start
        - identifier: customnav_graphingnav_events
          name: "Events"
          url: "/graphing/events/"
          weight: 30
          parent: menu_references_graphing
        - identifier: customnav_graphingnav_dashboards
          name: "Dashboards"
          url: "/graphing/dashboards/"
          weight: 40
          parent: menu_references_graphing
        - identifier: customnav_graphingnav_infrastructure
          name: "Infrastructure"
          url: "/graphing/infrastructure/"
          weight: 50
          parent: menu_references_graphing
        - identifier: customnav_infrastructurenav_hostmap
          name: "Hostmap"
          url: "/graphing/infrastructure/hostmap/"
          weight: 30
          parent: customnav_graphingnav_infrastructure
        - identifier: customnav_infrastructurenav_livecontainers
          name: "Live Containers"
          url: "/graphing/infrastructure/livecontainers/"
          weight: 40
          parent: customnav_graphingnav_infrastructure
        - identifier: customnav_infrastructurenav_process
          name: "Process"
          url: "/graphing/infrastructure/process/"
          weight: 50
          parent: customnav_graphingnav_infrastructure
        - identifier: customnav_graphingnav_metrics
          name: "Metrics"
          url: "/graphing/metrics/"
          weight: 60
          parent: menu_references_graphing
        - identifier: customnav_graphingnav_notebooks
          name: "Notebooks"
          url: "/graphing/notebooks/"
          weight: 70
          parent: menu_references_graphing
        - identifier: customnav_graphingnav_miscellaneous
          name: "Miscellaneous"
          url: "/graphing/miscellaneous/"
          weight: 80
          parent: menu_references_graphing
        # GRAPHING - Subnav end



        # ALERTING
        - identifier: menu_references_monitoring
          name: "Alerting"
          url: "/monitors/"
          pre: "nav_alerting"
          weight: 70
        # ALERTING - Subnav start
        - identifier: customnav_monitornav_monitor_types
          name: "Monitor Types"
          url: "/monitors/monitor_types/"
          weight: 30
          parent: menu_references_monitoring
        - identifier: customnav_monitortypenav_anomaly
          name: "Anomaly"
          url: "/monitors/monitor_types/anomaly/"
          weight: 20
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_apm
          name: "APM"
          url: "/monitors/monitor_types/apm/"
          weight: 30
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_composite
          name: "Composite"
          url: "/monitors/monitor_types/composite/"
          weight: 40
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_custom_check
          name: "Custom Check"
          url: "/monitors/monitor_types/custom_check/"
          weight: 50
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_event
          name: "Event"
          url: "/monitors/monitor_types/event/"
          weight: 60
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_host
          name: "Host"
          url: "/monitors/monitor_types/host/"
          weight: 70
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_integration
          name: "Integration"
          url: "/monitors/monitor_types/integration/"
          weight: 80
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_metric
          name: "Metric"
          url: "/monitors/monitor_types/metric/"
          weight: 90
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_network
          name: "Network"
          url: "/monitors/monitor_types/network/"
          weight: 100
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_outlier
          name: "Outlier"
          url: "/monitors/monitor_types/outlier/"
          weight: 110
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitortypenav_process
          name: "Process"
          url: "/monitors/monitor_types/process/"
          weight: 120
          parent: customnav_monitornav_monitor_types
        - identifier: customnav_monitornav_manage_monitor
          name: "Manage Monitor"
          url: "/monitors/manage_monitor/"
          weight: 40
          parent: menu_references_monitoring
        - identifier: customnav_monitornav_check_summary
          name: "Check Summary"
          url: "/monitors/check_summary/"
          weight: 50
          parent: menu_references_monitoring
        - identifier: customnav_monitornav_notifications
          name: "Notifications"
          url: "/monitors/notifications/"
          weight: 60
          parent: menu_references_monitoring
        - identifier: customnav_monitornav_downtimes
          name: "Downtimes"
          url: "/monitors/downtimes/"
          weight: 70
          parent: menu_references_monitoring
        - identifier: customnav_monitornav_faq
          name: "Faq"
          url: "/monitors/faq/"
          weight: 80
          parent: menu_references_monitoring
        # ALERTING - Subnav end


        # TRACING/APM
        - identifier: menu_references_tracing
          name: "Tracing/APM"
          url: "/tracing/"
          pre: "nav_tracing"
          weight: 80
        # TRACING/APM - Subnav start
        - identifier: customnav_tracingnav_terminology
          name: "Terminology"
          url: "/tracing/terminology/"
          weight: 10
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_environments
          name: "Environments"
          url: "/tracing/environments/"
          weight: 20
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_faq
          name: "Faq"
          url: "/tracing/faq/"
          weight: 30
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_help
          name: "Help"
          url: "/tracing/help/"
          weight: 40
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_langs
          name: "languages"
          url: "/tracing/languages/"
          weight: 50
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_go
          name: "Go"
          url: "/tracing/languages/go/"
          weight: 10
          parent: customnav_tracingnav_langs
        - identifier: customnav_tracingnav_python
          name: "Python"
          url: "/tracing/languages/python/"
          weight: 20
          parent: customnav_tracingnav_langs
        - identifier: customnav_tracingnav_ruby
          name: "Ruby"
          url: "/tracing/languages/ruby/"
          weight: 30
          parent: customnav_tracingnav_langs
        - identifier: customnav_tracingnav_docker
          name: "Docker"
          url: "/tracing/docker/"
          weight: 60
          parent: menu_references_tracing
        - identifier: customnav_tracingnav_api
          name: "Api"
          url: "/tracing/api/"
          weight: 70
          parent: menu_references_tracing
        # TRACING/APM - Subnav end


        # DEVELOPERS
        - identifier: menu_references_developers
          name: "Developers"
          url: "/developers/"
          pre: "nav_developers"
          weight: 100
        # DEVELOPERS - Subnav start
        - identifier: customnav_developersnav_api
          name: "Api"
          url: "/api/"
          weight: 30
          parent: menu_references_developers
        - identifier: customnav_developersnav_dogstatsd
          name: "Dogstatsd"
          url: "/developers/dogstatsd/"
          weight: 40
          parent: menu_references_developers
        - identifier: customnav_developersnav_libraries
          name: "Libraries"
          url: "/developers/libraries/"
          weight: 50
          parent: menu_references_developers
        - identifier: customnav_developersnav_integration_sdk
          name: "Integration SDK"
          url: "/developers/integration_sdk/"
          weight: 60
          parent: menu_references_developers
        - identifier: customnav_developersnav_metrics
          name: "Metrics"
          url: "/developers/metrics/"
          weight: 70
          parent: menu_references_developers
        - identifier: customnav_developersnav_metrictypes
          name: "Metric Types"
          url: "/developers/metrictypes/"
          weight: 80
          parent: menu_references_developers
        - identifier: customnav_developersnav_new_integration
          name: "New Integration"
          url: "/developers/new_integration/"
          weight: 90
          parent: menu_references_developers
        - identifier: customnav_developersnav_testing
          name: "Testing"
          url: "/developers/testing/"
          weight: 100
          parent: menu_references_developers
        - identifier: customnav_developersnav_units
          name: "Units"
          url: "/developers/units/"
          weight: 110
          parent: menu_references_developers
        # DEVELOPERS - Subnav end


        # ACCOUNT MANAGEMENT
        - identifier: menu_references_account_management
          name: "Account Management"
          url: "/account_management/"
          pre: "nav_account"
          weight: 90
        # ACCOUNT MANAGEMENT - Subnav start
        - identifier: customnav_accountmanagementnav_team
          name: "Team"
          url: "/account_management/team/"
          weight: 30
          parent: menu_references_account_management
        - identifier: customnav_accountmanagementnav_settings
          name: "Settings"
          url: "/account_management/settings/"
          weight: 40
          parent: menu_references_account_management
        - identifier: customnav_accountmanagementnav_saml
          name: "Saml"
          url: "/account_management/saml/"
          weight: 50
          parent: menu_references_account_management
        - identifier: customnav_accountmanagementnav_multi_account
          name: "Multi Account"
          url: "/account_management/multi_account/"
          weight: 60
          parent: menu_references_account_management
        - identifier: customnav_accountmanagementnav_faq
          name: "Faq"
          url: "/account_management/faq/"
          weight: 70
          parent: menu_references_account_management
        # ACCOUNT MANAGEMENT - Subnav end



        # LOGS
        - identifier: menu_references_logs
          name: "Logs"
          url: "/logs/"
          pre: "nav_start"
          weight: 110
        # LOGS - Subnav start
        - identifier: customnav_lognav_explore
          name: "Explore"
          url: "/logs/explore/"
          weight: 30
          parent: menu_references_logs
        - identifier: customnav_lognav_processing
          name: "Processing"
          url: "/logs/processing/"
          weight: 40
          parent: menu_references_logs
        - identifier: customnav_lognav_parsing
          name: "Parsing"
          url: "/logs/parsing/"
          weight: 50
          parent: menu_references_logs
        - identifier: customnav_lognav_aws
          name: "AWS"
          url: "/logs/aws/"
          weight: 60
          parent: menu_references_logs
        - identifier: customnav_lognav_languages
          name: "Languages"
          url: "/logs/languages/"
          weight: 70
          parent: menu_references_logs
        - identifier: customnav_lognav_java
          name: "Java"
          url: "/logs/languages/java/"
          weight: 70
          parent: customnav_lognav_languages
        - identifier: customnav_lognav_csharp
          name: "Csharp"
          url: "/logs/languages/csharp/"
          weight: 80
          parent: customnav_lognav_languages
        - identifier: customnav_lognav_go
          name: "Go"
          url: "/logs/languages/go/"
          weight: 90
          parent: customnav_lognav_languages
        - identifier: customnav_lognav_nodejs
          name: "Nodejs"
          url: "/logs/languages/nodejs/"
          weight: 100
          parent: customnav_lognav_languages
        - identifier: customnav_lognav_ruby
          name: "Ruby"
          url: "/logs/languages/ruby/"
          weight: 110
          parent: customnav_lognav_languages
        # LOGS - Subnav end




#        - identifier: menu_references_glossary
#          name: "Videos"
#          url: "/videos/"
#          pre: "nav_start"
#          weight: 120
#          hide: true
        - identifier: menu_references_glossary
          name: "Glossary"
          url: "/glossary/"
          pre: "nav_glossary"
          weight: 120
        - identifier: menu_references_faq
          name: "FAQ"
          url: "/faq/"
          pre: "nav_faq"
          weight: 130
        - identifier: menu_references_help
          name: "Help"
          url: "/help/"
          pre: "nav_start"
          weight: 140

params:
  environment: local
  img_url: "http://localhost:1313/"
  corp_url: "https://www.datadoghq.com/"
  imgix:
    header_jpg: "?ch=Width&fit=max&fm=jpg&auto=format&lossless=true"
    header_png: "?ch=Width&fit=max&fm=png&auto=format&lossless=1"
    header_gif: "?ch=Width,Save-Data&fm=gif"
    jpg: "?fm=jpg&auto=format&lossless=true"
    png: "?fm=png&auto=format&lossless=1"
    gif: ""
  static_url: "http://localhost:1313/"
  code_languages:
    - display_name: Python
      key: python
    - display_name: Ruby
      key: ruby
    - display_name: Curl
      key: console
  footer_scripts:
    - snowplow: false
    - marketo: false
    - adroll: false
  home:
      meta_image: datadog_logo_share_tt.png
      meta_title: Getting Started with Datadog
      meta_description: See metrics from all of your apps, tools &amp; services in one place with Datadog&#039;s cloud monitoring as a service solution. Try it for free.