environment: live
img_url: "https://d24im73ot8azv4.cloudfront.net/"
static_url: "https://docs.datadoghq.com/"
ga: UA-21102638-5

header_scripts:
  - hotjar: true
  - google-site-tag: true
  - google-tag-manager: true
  - marketo: true

footer_scripts:

hotjar:
  id: 1021060

