environment: preview
img_url: "https://datadog-docs-staging.imgix.net/"
static_url: "https://docs-staging.datadoghq.com/"
ga: UA-21102638-9

header_scripts:
  - datadog_monitoring: true
  - hotjar: true
  - google-tag-manager: true
  - marketo: true

datadog:
  clientToken: pub36877d3864fab670b5ae7e1d5d26cb08
  applicationId: c4e83ad8-4eda-4d2e-aae1-d943abce0463
  logging_handler: http

algolia:
  appId: EOIG7V0A2O
  apiKey: c7ec32b3838892b10610af30d06a4e42
  indexName: docsearch_docs_preview
