baseURL: 'http://localhost:1313/'
timeout: 100000
enableGitInfo: true

# default to just building english on local dev for a faster build
disableLanguages:
  - fr
  - ja
  - ko
  - es

server:
  redirects:
    - from: /studio/**
      to: /studio/404.html
      status: 404
    # default
    - from: /**
      to: /404.html
      status: 404
