environment: development
img_url: "http://localhost:1313/"
corp_url: "https://www.datadoghq.com/"
static_url: "http://localhost:1313/"


header_scripts:
  - hotjar: false
  - google-tag-manager: false
  - google-site-tag: false
  - marketo: false

footer_scripts:
  - snowplow: false

