---
baseURL: https://docs.datadoghq.com/
buildfuture: false
builddrafts: false
params:
  environment: live
  img_url: "https://datadog-docs.imgix.net/"
  static_url: "https://docs.datadoghq.com/"
  footer_scripts:
  - snowplow: true
  - marketo: true
  - adroll: true
