datadog:
  kubeStateMetricsEnabled: false
  leaderElection: true
  collectEvents: true
  logs:
    enabled: true
    containerCollectAll: true
  acExclude: "name:datadog-agent"
  orchestratorExplorer:
    enabled: false
agents:
  rbac:
    create: false
    serviceAccountName: datadog-agent
clusterAgent:
  enabled: false
