name: Send PR Approval Status

on:
  pull_request:
    branches:
      - master
    types: ["review_requested", "synchronize", "opened", "reopened"]
  pull_request_review:
    types:
      - submitted
      - dismissed

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  send_status:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.draft == false &&
      !contains(github.event.pull_request.labels.*.name, 'ci/skip') &&
      !contains(github.event.pull_request.head.ref, 'datadog-api-spec/test/') &&
      contains(github.event.pull_request.head.ref, 'datadog-api-spec/generated/')
    steps:
      - name: Get GitHub App token
        id: get_token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ secrets.PIPELINE_GITHUB_APP_ID }}
          private-key: ${{ secrets.PIPELINE_GITHUB_APP_PRIVATE_KEY }}
          repositories: datadog-api-spec
      - name: Post PR review status check
        uses: DataDog/github-actions/post-review-status@65b4875f33ad773d7ba4b005a2cb5f35020295f3 # v2.3.0
        with:
          github-token: ${{ steps.get_token.outputs.token }}
          repo: datadog-api-spec
          context: documentation/master
