name: Cache check
on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'local/bin/py/build/configurations/pull_config_preview.yaml'
      - 'local/bin/py/build/configurations/pull_config.yaml'

# Stop the current running job if a new push is made to the PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check-cache-values:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Find changed files
      id: changed_files
      uses: tj-actions/changed-files@v42
      with:
        separator: ','

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.10'
    - run: pip install pyyaml requests

    - name: Check pullconfig
      id: cache-values
      env:
        GH_EVENT: ${{ github.event_name }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CHECK_CACHE }}
        ALL_CHANGED_FILES: ${{ steps.changed_files.outputs.all_changed_files }}
      run: |
        python local/bin/py/check_cache_values.py \
        --files=$ALL_CHANGED_FILES
