name: Linting
on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: documentation

    - name: Clone Datadog Vale
      uses: actions/checkout@v3
      with:
        repository: DataDog/datadog-vale
        path: datadog-vale

    - run: | 
        pwd
        ls
        cd documentation
        ls
        
    - name: Find changed files
      id: changed_files
      uses: tj-actions/changed-files@v35
      with:
        separator: ","
        include_all_old_new_renamed_files: true
    
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        separator: ","
        reporter: github-pr-check
        fail_on_error: true
        filter_mode: diff_context
        files: ${{ steps.changed_files.outputs.all_changed_files }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
